sequenceDiagram
    participant Client
    participant lt as Load Test
    participant dp as datapool

    Client->>lt: Trigger load test method
    lt->>dp: Insert random data sequence
    lt->>dp: Sort data sequence
    Client->>dp: Ask server for datapool & SPT
    dp-->>Client: Return datapool & SPT
    Note over lt, dp: On OPC-UA server