." Man-page for dtsort program
." Written by Linus Sjöbro, lisj1502@student.miun.se

.TH dtsort 1 "2017-06-04" "V1.0" "dtsorter manual"

.SH NAME
dtsort - sort columns from a given text file

.SH SYNOPSIS
Use pipe to read a file:

dtsort [OPTION]...< FILE

Use options to read a file:

dtsort [OPTION]...-i FILE

.SH DESCRIPTION
Sort columns from a given textfile. The sorting can be affected through a number of different options.

See section
.B OPTIONS
for avaliable options.

Exampel:

dtsort -n -c2 -i file.txt -o file2.txt
.RS

This will sort the file
.B file.txt
after numbers at the second (2) column and output the sorted data into
.B file2.txt
.RE

.SH OPTIONS
Avaliable options for the program. With these options you can manipulate the sorting and printing

Input options:

.B .i, --input=file
.RS
Use option to input a file to the program insted of pipe (<) input
.RE


Sorting options:

.B -n, --numreric
.RS
Sort after numbers.
.RE

.B -r, --reverser
.RS
Sort the file reversed.
.RE

.B -c, --column=COLUMN
.RS
Choose wich column to sort after.
.RE

.B -d, --divider=DIVIDER
.RS
Choose what kind of divider that is used in the file. Standard divider is SPACE.
.RE


Print options:

.B -k, --keyonly
.RS
Print only the sorted column.
.RE

.B -o, --output=FILE
.RS
Print the sorted file to a new file.
.RE


Other options:

.B -h, --help
.RS
Display avaliable options and their description
.RE

.B -v, --version
.RS
Display the current version of the program
.RE

.SH DIAGNOSTICS
What kind of errors can the program gives you?

.B No file as input
.RS
This means that no file is insertet into the program. Either via piping of option arguments.
.RE

.B File does not exist!
.RS
The given file with the
.B -i
option is not found.

Neither a misspelling or the file does not exist in the current folder.
.RE

.B Given column is not a number!
.RS
The given column in the file does not start with a number.

To sort this file at that specific column, remove the -n option.
.RE

.SH AUTHOR
Written by Linus Sjobro

lisj1502@studen.miun.se

linussjobro@gmail.com
