main: main.cpp file_handling.cpp file_handling.h main_menu.cpp main_menu.h contacts_handling.cpp contacts_handling.h search.cpp search.h
	clear
	g++ -std=c++11 -o main main.cpp file_handling.cpp main_menu.cpp contacts_handling.cpp search.cpp

run: main
	clear
	@./main




